#!/bin/bash

set -e

exec 3>&1 # move stdout to 3 for returning our output
exec 1>&2 # redirect normal output to stderr for logging

stage_version(){
  touch $destination/count
  echo "$count" > $destination/count
}

main(){
  destination=$1
  payload=$(mktemp /tmp/resource-in.XXXXXX)
  cat > $payload <&0
  count=$(jq -r '.version.count' < $payload)

  if [[ "null" == "$count" ]]; then
    echo "Could not find version inforation. A verison must be specified." >&2
    exit 1
  fi

  stage_version $count

  jq -M -n "{
    version: {
      count: $(echo $count | jq -R . )
    }
  }" >&3
}

main $1
